"use client";

import React, { useState } from "react";
import { Button } from "@/Components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { SessionDetail } from "../medical-agent/[sessionId]/page";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

type Props = {
  record: SessionDetail;
  variant?: "outline" | "default" | "link";
  showText?: boolean;
};

export default function DownloadReportButton({ record, variant = "outline", showText = false }: Props) {
  const [loading, setLoading] = useState(false);

  const handleDownload = async (e: React.MouseEvent) => {
    e.stopPropagation();
    setLoading(true);

    try {
      // 1. Get the report data if not already fully present
      let reportData = record.report as any;
      if (!reportData || !reportData.summary) {
        const res = await fetch(`/api/session-chat?sessionId=${record.sessionId}`);
        const sessionData = await res.json();
        
        const reportRes = await fetch("/api/medical-report", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            sessionId: record.sessionId,
            sessionDetail: record.selectedDoctor,
            messages: sessionData.conversation,
          }),
        });
        reportData = await reportRes.json();
      }

      // 2. Create a temporary hidden element for PDF generation
      const element = document.createElement("div");
      element.style.padding = "40px";
      element.style.width = "800px";
      element.style.position = "absolute";
      element.style.left = "-9999px";
      element.style.backgroundColor = "white";
      element.style.color = "black";
      element.style.fontFamily = "sans-serif";

      element.innerHTML = `
        <div style="border: 2px solid #2563eb; padding: 30px; border-radius: 10px;">
          <h1 style="color: #2563eb; text-align: center; margin-bottom: 30px;">🩺 Medical AI Voice Agent Report</h1>
          
          <div style="margin-bottom: 25px; display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
            <p><strong>Doctor Specialist:</strong> ${record.selectedDoctor?.specialist || 'N/A'}</p>
            <p><strong>Consult Date:</strong> ${new Date(record.createdOn).toLocaleDateString()}</p>
            <p><strong>User:</strong> ${reportData?.user || "Anonymous"}</p>
            <p><strong>Report ID:</strong> ${record.sessionId}</p>
          </div>

          <div style="margin-bottom: 20px;">
            <h3 style="color: #2563eb; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px;">Chief Complaint</h3>
            <p>${reportData?.chiefComplaint || "N/A"}</p>
          </div>

          <div style="margin-bottom: 20px;">
            <h3 style="color: #2563eb; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px;">Summary</h3>
            <p>${reportData?.summary || "N/A"}</p>
          </div>

          <div style="margin-bottom: 20px;">
            <h3 style="color: #2563eb; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px;">Symptoms</h3>
            <p>${Array.isArray(reportData?.symptoms) ? reportData.symptoms.join(", ") : "None reported"}</p>
          </div>

          <div style="margin-bottom: 20px; display: grid; grid-template-columns: 1fr 1fr;">
            <p><strong>Duration:</strong> ${reportData?.duration || "N/A"}</p>
            <p><strong>Severity:</strong> ${reportData?.severity || "N/A"}</p>
          </div>

          <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ef4444; color: #ef4444; font-size: 12px; font-style: italic;">
            Disclaimer: This report was generated by an AI Medical Assistant for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.
          </div>
        </div>
      `;

      document.body.appendChild(element);

      // 3. Generate PDF
      const canvas = await html2canvas(element, { scale: 2 });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      pdf.save(`Medical_Report_${record.sessionId.slice(0, 8)}.pdf`);

      document.body.removeChild(element);
    } catch (error) {
      console.error("PDF Generation failed:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button 
      variant={variant} 
      size={showText ? "default" : "icon"} 
      className={showText ? "gap-2" : "h-8 w-8 text-blue-600 border-blue-200 hover:bg-blue-50"} 
      onClick={handleDownload}
      disabled={loading}
    >
      {loading ? (
        <Loader2 className="h-4 w-4 animate-spin text-blue-600" />
      ) : (
        <>
          <Download className="h-4 w-4" />
          {showText && "Download PDF"}
        </>
      )}
    </Button>
  );
}
