"use client";

import React, { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/Components/ui/dialog";
import { Button } from "@/Components/ui/button";
import { SessionDetail } from "../medical-agent/[sessionId]/page";
import moment from "moment";

type Props = {
  record: SessionDetail;
};



export default function ViewReportDialog({ record }: Props) {
  const [report, setReport] = useState<any>(record.report || null);
  const [loading, setLoading] = useState(false);



    const generateReport = async () => {
    if (report) return; // Already available, skip fetch

    setLoading(true);
      try {
         // 1. Get full session (includes messages)
      const sessionRes = await fetch(`/api/session-chat?sessionId=${record.sessionId}`);
      const sessionData = await sessionRes.json();

      if (!sessionData?.conversation) {
        console.warn("No conversation found for session");
        setLoading(false);
        return;
      }
        const res = await fetch("/api/medical-report", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            sessionId: record.sessionId,
            sessionDetail: record.selectedDoctor,
            messages:  sessionData.conversation,
          }),
        });

        const data = await res.json();
         setReport(data);
      } catch (err) {
        console.error("Failed to load report:", err);
      } finally {
        setLoading(false);
      }
    };



  return (
    <div>
      <Dialog>
        <DialogTrigger asChild>
          <Button variant="link" size="sm" onClick={generateReport}>
            {loading ? "Loading..." : "View Report"}
          </Button>
        </DialogTrigger>

        <DialogContent className="max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle asChild>
              <h2 className="text-center text-4xl">🩺 Medical AI Voice Agent Report</h2>
            </DialogTitle>
            <DialogDescription asChild>
             <div className="mt-10 space-y-6 text-base">
                {/* Session Info */}
                <div>
                  <h2 className="font-bold text-blue-500 text-lg">Session Info:</h2>
                  <div className="grid grid-cols-2 gap-y-1 mt-2">
                    <div><strong>Doctor Specialization:</strong> {record.selectedDoctor?.specialist}</div>
                    <div><strong>User:</strong> {report?.user || "Anonymous"}</div>
                    <div><strong>Consult Date:</strong> {moment(new Date(record?.createdOn)).fromNow()}</div>
                    <div><strong>Agent:</strong> {report?.agent || "General Physician AI"}</div>
                  </div>
                </div>

                {/* Report Sections */}
                <div>
                  <h3 className="font-bold text-blue-600 text-lg border-b pb-1">Chief Complaint</h3>
                  <p className="mt-2">{report?.chiefComplaint || "The user did not clearly state a chief compliant in this intial interaction"}</p>
                </div>

                <div>
                  <h3 className="font-bold text-blue-600 text-lg border-b pb-1">Summary</h3>
                  <p className="mt-2">{report?.summary || "The AI medical assistant introduced itself and asked the user how they were feeling.The user has not yet provided any specific symptoms or concerns."}</p>
                </div>

                <div>
                  <h3 className="font-bold text-blue-600 text-lg border-b pb-1">Symptoms</h3>
                  <p className="mt-2">
                    {Array.isArray(report?.symptoms) && report.symptoms.length > 0
                      ? report.symptoms.join(", ")
                      : "None reported"}
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-blue-600 text-lg border-b pb-1">Duration & Severity</h3>
                  <div className="grid grid-cols-2 mt-2">
                    <div><strong>Duration:</strong> {report?.duration || "Not Specified"}</div>
                    <div><strong>Severity:</strong> {report?.severity || "Not Specified"}</div>
                  </div>
                </div>

                {/* Footer */}
                <div className="text-sm text-red-500 pt-4 border-t">
                  This report was generated by an AI Medical Assistant for informational purposes only.
                </div>
              </div>
            </DialogDescription>
          </DialogHeader>
        </DialogContent>
      </Dialog>
    </div>
  );
}
